[project]
name = "init-repo-template-uv"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"


[dependency-groups]
dev = [
    "cookiecutter>=2.6.0",
    "pre-commit>=4.1.0",
]
