[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=3.7.1",
    "ruff>=0.4.6",
    "pytest>=8.3.3",
    "loguru>=0.7.2",
    "click>=8.1.7",
]
